# Generated by Django 3.1.3 on 2020-11-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookName', models.CharField(max_length=50)),
                ('BookId', models.IntegerField(null=True)),
                ('BookAuthor', models.CharField(max_length=50)),
                ('BookImage', models.ImageField(null=True, upload_to='bookimages')),
            ],
        ),
    ]
